### ISSUE TITLE
Container won't build: firefox-esr:amd64 has unmet dependencies

### ISSUE THREAD

**Issue by kostecky** [niclan/Javafox#19] opened 2024-03-04 00:11 UTC
I can't seem to build the container:

```
[+] Building 1.0s (8/13)                                                                                                                                                                  docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                                      0.0s
 => => transferring dockerfile: 1.46kB                                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:16.04                                                                                                                                           0.2s
 => [internal] load .dockerignore                                                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                                                           0.0s
 => [1/9] FROM docker.io/library/ubuntu:16.04@sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6                                                                                     0.0s
 => [internal] load build context                                                                                                                                                                         0.0s
 => => transferring context: 393B                                                                                                                                                                         0.0s
 => CACHED [2/9] RUN apt-get -q update &&     apt-get -qy dist-upgrade &&     apt-get -qy install libterm-readline-perl-perl dialog &&     apt-get -qy install sudo apt-utils software-properties-common  0.0s
 => CACHED [3/9] COPY deb/* /tmp/                                                                                                                                                                         0.0s
 => ERROR [4/9] RUN apt-get -y install /tmp/*.deb                                                                                                                                                         0.7s
------
 > [4/9] RUN apt-get -y install /tmp/*.deb:
0.111 Reading package lists...
0.552 Building dependency tree...
0.634 Reading state information...
0.658 Some packages could not be installed. This may mean that you have
0.658 requested an impossible situation or if you are using the unstable
0.658 distribution that some required packages have not yet been created
0.658 or been moved out of Incoming.
0.658 The following information may help to resolve the situation:
0.658
0.658 The following packages have unmet dependencies:
0.698  firefox-esr:amd64 : Depends: libasound2:amd64 (>= 1.0.16) but it is not installable
0.698                      Depends: libatk1.0-0:amd64 (>= 1.12.4) but it is not installable
0.698                      Depends: libc6:amd64 (>= 2.17) but it is not installable
0.698                      Depends: libcairo-gobject2:amd64 (>= 1.10.0) but it is not installable
0.698                      Depends: libcairo2:amd64 (>= 1.10.0) but it is not installable
0.698                      Depends: libdbus-1-3:amd64 (>= 1.0.2) but it is not installable
0.698                      Depends: libdbus-glib-1-2:amd64 (>= 0.78) but it is not installable
0.698                      Depends: libffi6:amd64 (>= 3.0.4) but it is not installable
0.698                      Depends: libfontconfig1:amd64 (>= 2.9.0) but it is not installable
0.698                      Depends: libfreetype6:amd64 (>= 2.2.1) but it is not installable
0.698                      Depends: libgcc1:amd64 (>= 1:4.1.1) but it is not installable
0.698                      Depends: libgdk-pixbuf2.0-0:amd64 (>= 2.22.0) but it is not installable
0.698                      Depends: libglib2.0-0:amd64 (>= 2.31.8) but it is not installable
0.698                      Depends: libgtk-3-0:amd64 (>= 3.0.0) but it is not installable
0.698                      Depends: libgtk2.0-0:amd64 (>= 2.10) but it is not installable
0.698                      Depends: libpango-1.0-0:amd64 (>= 1.14.0) but it is not installable
0.698                      Depends: libstartup-notification0:amd64 (>= 0.8) but it is not installable
0.698                      Depends: libstdc++6:amd64 (>= 4.6) but it is not installable
0.698                      Depends: libx11-6:amd64 but it is not installable
0.698                      Depends: libx11-xcb1:amd64 but it is not installable
0.698                      Depends: libxcb-shm0:amd64 but it is not installable
0.698                      Depends: libxcb1:amd64 but it is not installable
0.698                      Depends: libxcomposite1:amd64 (>= 1:0.3-1) but it is not installable
0.698                      Depends: libxdamage1:amd64 (>= 1:1.1) but it is not installable
0.698                      Depends: libxext6:amd64 but it is not installable
0.698                      Depends: libxfixes3:amd64 but it is not installable
0.698                      Depends: libxrender1:amd64 but it is not installable
0.698                      Depends: libxt6:amd64 but it is not installable
0.698                      Depends: zlib1g:amd64 (>= 1:1.2.3.4) but it is not installable
0.698                      Depends: libsqlite3-0:amd64 (>= 3.7.12-1~) but it is not installable
0.698  libevent-2.0-5:amd64 : Depends: libc6:amd64 (>= 2.17) but it is not installable
0.698  libhunspell-1.3-0:amd64 : Depends: libc6:amd64 (>= 2.14) but it is not installable
0.698                            Depends: libgcc1:amd64 (>= 1:3.0) but it is not installable
0.698                            Depends: libstdc++6:amd64 (>= 5.2) but it is not installable
0.698                            Recommends: hunspell-en-us:amd64 but it is not installable or
0.698                                        hunspell-dictionary:amd64 but it is not installable or
0.698                                        myspell-dictionary:amd64 but it is not installable
0.698  libjsoncpp0:amd64 : Depends: libc6:amd64 (>= 2.14) but it is not installable
0.698                      Depends: libgcc1:amd64 (>= 1:4.1.1) but it is not installable
0.698                      Depends: libstdc++6:amd64 (>= 4.1.1) but it is not installable
0.698  libvpx3:amd64 : Depends: libc6:amd64 (>= 2.14) but it is not installable
0.703 E: Unable to correct problems, you have held broken packages.
------
Dockerfile:13
--------------------
  11 |     COPY deb/* /tmp/
  12 |
  13 | >>> RUN apt-get -y install /tmp/*.deb
  14 |
  15 |     RUN useradd -m -s /bin/bash -c "Firefox user" ffuser && \
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get -y install /tmp/*.deb" did not complete successfully: exit code: 100
```

**Comment by niclan** [comment] 2024-03-05 12:55
Hi,

It builds fine for me:
```
Step 1/13 : FROM ubuntu:16.04
16.04: Pulling from library/ubuntu
58690f9b18fc: Pull complete 
b51569e7c507: Pull complete 
da8ef40b9eca: Pull complete 
fb15d46c38dc: Pull complete 
Digest: sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6
Status: Downloaded newer image for ubuntu:16.04
 ---> b6f507652425
Step 2/13 : ENV TZ=GMT
 ---> Running in 1a2c722a0f70
Removing intermediate container 1a2c722a0f70
 ---> 372353b505d6
Step 3/13 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Running in 892b39057cd8
Removing intermediate container 892b39057cd8
 ---> b4d127633984
Step 4/13 : RUN apt-get -q update &&     apt-get -qy dist-upgrade &&     apt-get -qy install libterm-readline-perl-perl dialog &&     apt-get -qy install sudo apt-utils software-properties-common xauth dialog
 ---> Running in 6768ff316fe7
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [99.8 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [1150 kB]
...
 ---> 22e2d6bb0bea
Step 5/13 : COPY deb/* /tmp/
 ---> 9fa56fc79764
Step 6/13 : RUN apt-get -y install /tmp/*.deb
 ---> Running in ff54d1f73b1e
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  acl adwaita-icon-theme at-spi2-core colord colord-data
  dconf-gsettings-backend dconf-service dictionaries-common emacsen-common
...
After this operation, 427 MB of additional disk space will be used.
Get:1 /tmp/libjsoncpp0_0.6.0~rc2-3.1_amd64.deb libjsoncpp0 amd64 0.6.0~rc2-3.1 [71.8 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 fonts-dejavu-core all 2.35-1 [1039 kB]
Get:3 /tmp/firefox-esr_52.9.0esr-1~14.04.york0_amd64.deb firefox-esr amd64 52.9.0esr-1~14.04.york0 [46.7 MB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 fontconfig-config all 2.11.94-0ubuntu1.1 [49.9 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpng12-0 amd64 1.2.54-1ubuntu1.1 [116 kB]
...
```

If you can clear your docker cache:
 
```console
$ docker rmi ubuntu:16.04
Untagged: ubuntu:16.04
Untagged: ubuntu@sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6
$ docker image prune
WARNING! This will remove all dangling images.
Are you sure you want to continue? [y/N] y
Deleted Images:
deleted: sha256:b529adb9bac9468e05ecb4d7bc8a146178f8175fdcf226336b011cdfdbba75a9
...
```

and then capture the the build log to show what repositories apt-get are using to get packages from.  It seems likely that the ubuntu repository the image decides to use no longer carries 16.04 packages

**Comment by NoahJaehnert** [comment] 2024-03-09 15:27
I'm getting the same error, see below for build output: 

```
Javafox-master % docker build -t javafox .
[+] Building 27.3s (8/13)                                                                                                                                              docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                   0.0s
 => => transferring dockerfile: 1.51kB                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/ubuntu:16.04                                                                                                                        0.6s
 => [internal] load .dockerignore                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                        0.0s
 => [1/9] FROM docker.io/library/ubuntu:16.04@sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6                                                                  2.9s
 => => resolve docker.io/library/ubuntu:16.04@sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6                                                                  0.0s
 => => sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6 1.42kB / 1.42kB                                                                                         0.0s
 => => sha256:f4c51ba054967fd4b06715f1b67078efbe9ca152e8be98d8f3c1f4d08c6042f8 1.15kB / 1.15kB                                                                                         0.0s
 => => sha256:d125c6a1fe22504f84552b7eb11e353e88691875c18caf68847843892b190ccc 3.38kB / 3.38kB                                                                                         0.0s
 => => sha256:828b35a09f0b2f3d1dead43aa2468ff5eba6c463423b3fff7ee6d150f6fd1b6b 41.24MB / 41.24MB                                                                                       1.7s
 => => sha256:66927c6d1d3d2e9321c4893f7f2105b7cd23dfb082853d97ec08f188e271e612 854B / 854B                                                                                             0.2s
 => => sha256:000560be91651dcbf476ebacb8bf1f1339694a3327f8e6da2519e0b29b33eb5d 479B / 479B                                                                                             0.3s
 => => sha256:6225a0253717abdc2ee23ea211c1c439c93b84231ec0a4f1c74762a205ba7234 173B / 173B                                                                                             0.3s
 => => extracting sha256:828b35a09f0b2f3d1dead43aa2468ff5eba6c463423b3fff7ee6d150f6fd1b6b                                                                                              1.1s
 => => extracting sha256:66927c6d1d3d2e9321c4893f7f2105b7cd23dfb082853d97ec08f188e271e612                                                                                              0.0s
 => => extracting sha256:000560be91651dcbf476ebacb8bf1f1339694a3327f8e6da2519e0b29b33eb5d                                                                                              0.0s
 => => extracting sha256:6225a0253717abdc2ee23ea211c1c439c93b84231ec0a4f1c74762a205ba7234                                                                                              0.0s
 => [internal] load build context                                                                                                                                                      0.2s
 => => transferring context: 47.71MB                                                                                                                                                   0.2s
 => [2/9] RUN apt-get -q update &&     apt-get -qy dist-upgrade &&     apt-get -qy install libterm-readline-perl-perl dialog &&     apt-get -qy install sudo apt-utils software-prop  23.1s
 => [3/9] COPY deb/* /tmp/                                                                                                                                                             0.0s
 => ERROR [4/9] RUN apt-get -y install /tmp/*.deb                                                                                                                                      0.7s
------
 > [4/9] RUN apt-get -y install /tmp/*.deb:
0.090 Reading package lists...
0.527 Building dependency tree...
0.593 Reading state information...
0.613 Some packages could not be installed. This may mean that you have
0.613 requested an impossible situation or if you are using the unstable
0.613 distribution that some required packages have not yet been created
0.613 or been moved out of Incoming.
0.613 The following information may help to resolve the situation:
0.613
0.613 The following packages have unmet dependencies:
0.642  firefox-esr:amd64 : Depends: libasound2:amd64 (>= 1.0.16) but it is not installable
0.642                      Depends: libatk1.0-0:amd64 (>= 1.12.4) but it is not installable
0.642                      Depends: libc6:amd64 (>= 2.17) but it is not installable
0.642                      Depends: libcairo-gobject2:amd64 (>= 1.10.0) but it is not installable
0.642                      Depends: libcairo2:amd64 (>= 1.10.0) but it is not installable
0.642                      Depends: libdbus-1-3:amd64 (>= 1.0.2) but it is not installable
0.642                      Depends: libdbus-glib-1-2:amd64 (>= 0.78) but it is not installable
0.642                      Depends: libffi6:amd64 (>= 3.0.4) but it is not installable
0.642                      Depends: libfontconfig1:amd64 (>= 2.9.0) but it is not installable
0.642                      Depends: libfreetype6:amd64 (>= 2.2.1) but it is not installable
0.642                      Depends: libgcc1:amd64 (>= 1:4.1.1) but it is not installable
0.642                      Depends: libgdk-pixbuf2.0-0:amd64 (>= 2.22.0) but it is not installable
0.642                      Depends: libglib2.0-0:amd64 (>= 2.31.8) but it is not installable
0.642                      Depends: libgtk-3-0:amd64 (>= 3.0.0) but it is not installable
0.642                      Depends: libgtk2.0-0:amd64 (>= 2.10) but it is not installable
0.642                      Depends: libpango-1.0-0:amd64 (>= 1.14.0) but it is not installable
0.642                      Depends: libstartup-notification0:amd64 (>= 0.8) but it is not installable
0.642                      Depends: libstdc++6:amd64 (>= 4.6) but it is not installable
0.642                      Depends: libx11-6:amd64 but it is not installable
0.642                      Depends: libx11-xcb1:amd64 but it is not installable
0.642                      Depends: libxcb-shm0:amd64 but it is not installable
0.642                      Depends: libxcb1:amd64 but it is not installable
0.642                      Depends: libxcomposite1:amd64 (>= 1:0.3-1) but it is not installable
0.642                      Depends: libxdamage1:amd64 (>= 1:1.1) but it is not installable
0.642                      Depends: libxext6:amd64 but it is not installable
0.642                      Depends: libxfixes3:amd64 but it is not installable
0.642                      Depends: libxrender1:amd64 but it is not installable
0.642                      Depends: libxt6:amd64 but it is not installable
0.642                      Depends: zlib1g:amd64 (>= 1:1.2.3.4) but it is not installable
0.642                      Depends: libsqlite3-0:amd64 (>= 3.7.12-1~) but it is not installable
0.642  libevent-2.0-5:amd64 : Depends: libc6:amd64 (>= 2.17) but it is not installable
0.642  libhunspell-1.3-0:amd64 : Depends: libc6:amd64 (>= 2.14) but it is not installable
0.642                            Depends: libgcc1:amd64 (>= 1:3.0) but it is not installable
0.642                            Depends: libstdc++6:amd64 (>= 5.2) but it is not installable
0.642                            Recommends: hunspell-en-us:amd64 but it is not installable or
0.642                                        hunspell-dictionary:amd64 but it is not installable or
0.642                                        myspell-dictionary:amd64 but it is not installable
0.642  libjsoncpp0:amd64 : Depends: libc6:amd64 (>= 2.14) but it is not installable
0.642                      Depends: libgcc1:amd64 (>= 1:4.1.1) but it is not installable
0.642                      Depends: libstdc++6:amd64 (>= 4.1.1) but it is not installable
0.642  libvpx3:amd64 : Depends: libc6:amd64 (>= 2.14) but it is not installable
0.645 E: Unable to correct problems, you have held broken packages.
------
Dockerfile:13
--------------------
  11 |     COPY deb/* /tmp/
  12 |
  13 | >>> RUN apt-get -y install /tmp/*.deb
  14 |
  15 |     RUN useradd -m -s /bin/bash -c "Firefox user" ffuser && \
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get -y install /tmp/*.deb" did not complete successfully: exit code: 100
```

**Comment by NoahJaehnert** [comment] 2024-03-09 15:32
Build.log attached
[build.log](https://github.com/niclan/Javafox/files/14546795/build.log)

**Comment by niclan** [comment] 2024-03-18 14:40
Hi,

Your log shows a perfectly normal build, including installing debian packages via networking up until installing the firefox packages from the locally cached *.deb files.  This is weird and I can't reproduce the problem.

This would _usually_ be the result of stale apt package index caches in the container.  BUT that seems not to be the case here because the Dockerfile starts by doing `apt-get -q update` which updates the package indexes, and then the dist-upgrade and package installs after that work well. 

The other possibility is that it somehow chooses a http://ports.ubuntu.com/ubuntu-ports which was already stale in 2018 or something.  My install process uses http://archive.ubuntu.com/ubuntu and when I look inside the ubuntu 16.04 image I find this:

```console
$ docker run --rm -it ubuntu:16.04 grep -v \# /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu/ xenial main restricted

deb http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted

deb http://archive.ubuntu.com/ubuntu/ xenial universe
deb http://archive.ubuntu.com/ubuntu/ xenial-updates universe

deb http://archive.ubuntu.com/ubuntu/ xenial multiverse
deb http://archive.ubuntu.com/ubuntu/ xenial-updates multiverse

deb http://archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu/ xenial-security main restricted
deb http://security.ubuntu.com/ubuntu/ xenial-security universe
deb http://security.ubuntu.com/ubuntu/ xenial-security multiverse
```

so it looks to me like you have a stale ubuntu:16.04 image referring to a stale apt-repository.  If you capture the lines I show above starting in `deb` into `sources.list` in the Javafox root directory and then add this line to Dockerfile:

```
COPY sources.list /etc/apt/sources.list                                                                               
```

right before `RUN apt-get -y update && \` then that _might_ fix it.

**Comment by niclan** [comment] 2024-03-18 14:43
And if that works I'll put it into the standard Dockerfile.

**Comment by NoahJaehnert** [comment] 2024-03-27 16:28
Still getting errors even after your suggestions above. Also did a docker system prune prior to building: 

```
[+] Building 6.7s (7/14)                                                                                                                                                  docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                      0.0s
 => => transferring dockerfile: 1.69kB                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:16.04                                                                                                                           1.2s
 => [internal] load .dockerignore                                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                                           0.0s
 => [ 1/10] FROM docker.io/library/ubuntu:16.04@sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6                                                                   3.0s
 => => resolve docker.io/library/ubuntu:16.04@sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6                                                                     0.0s
 => => sha256:d125c6a1fe22504f84552b7eb11e353e88691875c18caf68847843892b190ccc 3.38kB / 3.38kB                                                                                            0.0s
 => => sha256:828b35a09f0b2f3d1dead43aa2468ff5eba6c463423b3fff7ee6d150f6fd1b6b 41.24MB / 41.24MB                                                                                          1.7s
 => => sha256:66927c6d1d3d2e9321c4893f7f2105b7cd23dfb082853d97ec08f188e271e612 854B / 854B                                                                                                0.2s
 => => sha256:000560be91651dcbf476ebacb8bf1f1339694a3327f8e6da2519e0b29b33eb5d 479B / 479B                                                                                                0.4s
 => => sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d6 1.42kB / 1.42kB                                                                                            0.0s
 => => sha256:f4c51ba054967fd4b06715f1b67078efbe9ca152e8be98d8f3c1f4d08c6042f8 1.15kB / 1.15kB                                                                                            0.0s
 => => sha256:6225a0253717abdc2ee23ea211c1c439c93b84231ec0a4f1c74762a205ba7234 173B / 173B                                                                                                0.5s
 => => extracting sha256:828b35a09f0b2f3d1dead43aa2468ff5eba6c463423b3fff7ee6d150f6fd1b6b                                                                                                 1.1s
 => => extracting sha256:66927c6d1d3d2e9321c4893f7f2105b7cd23dfb082853d97ec08f188e271e612                                                                                                 0.0s
 => => extracting sha256:000560be91651dcbf476ebacb8bf1f1339694a3327f8e6da2519e0b29b33eb5d                                                                                                 0.0s
 => => extracting sha256:6225a0253717abdc2ee23ea211c1c439c93b84231ec0a4f1c74762a205ba7234                                                                                                 0.0s
 => [internal] load build context                                                                                                                                                         0.2s
 => => transferring context: 47.71MB                                                                                                                                                      0.2s
 => [ 2/10] COPY sources.list /etc/apt/sources.list                                                                                                                                       0.1s
 => ERROR [ 3/10] RUN apt-get -q update &&     apt-get -qy dist-upgrade &&     apt-get -qy install libterm-readline-perl-perl dialog &&     apt-get -qy install sudo apt-utils software-  2.2s
------
 > [ 3/10] RUN apt-get -q update &&     apt-get -qy dist-upgrade &&     apt-get -qy install libterm-readline-perl-perl dialog &&     apt-get -qy install sudo apt-utils software-properties-common xauth dialog:
0.436 Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [99.8 kB]
0.503 Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
0.607 Ign:3 http://security.ubuntu.com/ubuntu xenial-security/main arm64 Packages
0.644 Ign:4 http://security.ubuntu.com/ubuntu xenial-security/universe arm64 Packages
0.644 Ign:5 http://security.ubuntu.com/ubuntu xenial-security/multiverse arm64 Packages
0.715 Ign:3 http://security.ubuntu.com/ubuntu xenial-security/main arm64 Packages
0.715 Ign:4 http://security.ubuntu.com/ubuntu xenial-security/universe arm64 Packages
0.759 Ign:5 http://security.ubuntu.com/ubuntu xenial-security/multiverse arm64 Packages
0.759 Ign:3 http://security.ubuntu.com/ubuntu xenial-security/main arm64 Packages
0.800 Ign:4 http://security.ubuntu.com/ubuntu xenial-security/universe arm64 Packages
0.800 Ign:5 http://security.ubuntu.com/ubuntu xenial-security/multiverse arm64 Packages
0.904 Err:3 http://security.ubuntu.com/ubuntu xenial-security/main arm64 Packages
0.904   404  Not Found [IP: 185.125.190.36 80]
0.904 Ign:4 http://security.ubuntu.com/ubuntu xenial-security/universe arm64 Packages
0.950 Ign:5 http://security.ubuntu.com/ubuntu xenial-security/multiverse arm64 Packages
1.117 Get:6 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [99.8 kB]
1.254 Get:7 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [97.4 kB]
1.281 Ign:8 http://archive.ubuntu.com/ubuntu xenial/main arm64 Packages
1.281 Ign:9 http://archive.ubuntu.com/ubuntu xenial/universe arm64 Packages
1.281 Ign:10 http://archive.ubuntu.com/ubuntu xenial/multiverse arm64 Packages
1.423 Ign:11 http://archive.ubuntu.com/ubuntu xenial-updates/main arm64 Packages
1.656 Ign:12 http://archive.ubuntu.com/ubuntu xenial-updates/universe arm64 Packages
1.656 Ign:13 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse arm64 Packages
1.656 Ign:8 http://archive.ubuntu.com/ubuntu xenial/main arm64 Packages
1.656 Ign:9 http://archive.ubuntu.com/ubuntu xenial/universe arm64 Packages
1.748 Ign:10 http://archive.ubuntu.com/ubuntu xenial/multiverse arm64 Packages
1.748 Ign:14 http://archive.ubuntu.com/ubuntu xenial-backports/main arm64 Packages
1.748 Ign:15 http://archive.ubuntu.com/ubuntu xenial-backports/universe arm64 Packages
1.844 Ign:11 http://archive.ubuntu.com/ubuntu xenial-updates/main arm64 Packages
2.022 Ign:12 http://archive.ubuntu.com/ubuntu xenial-updates/universe arm64 Packages
2.022 Ign:13 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse arm64 Packages
2.022 Ign:8 http://archive.ubuntu.com/ubuntu xenial/main arm64 Packages
2.022 Ign:9 http://archive.ubuntu.com/ubuntu xenial/universe arm64 Packages
2.022 Ign:10 http://archive.ubuntu.com/ubuntu xenial/multiverse arm64 Packages
2.022 Ign:14 http://archive.ubuntu.com/ubuntu xenial-backports/main arm64 Packages
2.022 Ign:15 http://archive.ubuntu.com/ubuntu xenial-backports/universe arm64 Packages
2.065 Ign:11 http://archive.ubuntu.com/ubuntu xenial-updates/main arm64 Packages
2.065 Ign:12 http://archive.ubuntu.com/ubuntu xenial-updates/universe arm64 Packages
2.065 Ign:13 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse arm64 Packages
2.065 Err:8 http://archive.ubuntu.com/ubuntu xenial/main arm64 Packages
2.065   404  Not Found [IP: 185.125.190.39 80]
2.065 Ign:9 http://archive.ubuntu.com/ubuntu xenial/universe arm64 Packages
2.065 Ign:10 http://archive.ubuntu.com/ubuntu xenial/multiverse arm64 Packages
2.065 Ign:14 http://archive.ubuntu.com/ubuntu xenial-backports/main arm64 Packages
2.104 Ign:15 http://archive.ubuntu.com/ubuntu xenial-backports/universe arm64 Packages
2.104 Err:11 http://archive.ubuntu.com/ubuntu xenial-updates/main arm64 Packages
2.104   404  Not Found [IP: 185.125.190.39 80]
2.105 Ign:12 http://archive.ubuntu.com/ubuntu xenial-updates/universe arm64 Packages
2.105 Ign:13 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse arm64 Packages
2.195 Err:14 http://archive.ubuntu.com/ubuntu xenial-backports/main arm64 Packages
2.195   404  Not Found [IP: 185.125.190.39 80]
2.195 Ign:15 http://archive.ubuntu.com/ubuntu xenial-backports/universe arm64 Packages
2.209 Fetched 544 kB in 2s (257 kB/s)
2.209 Reading package lists...
2.216 E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/binary-arm64/Packages  404  Not Found [IP: 185.125.190.36 80]
2.216 E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/main/binary-arm64/Packages  404  Not Found [IP: 185.125.190.39 80]
2.216 E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-arm64/Packages  404  Not Found [IP: 185.125.190.39 80]
2.216 E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/main/binary-arm64/Packages  404  Not Found [IP: 185.125.190.39 80]
2.216 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
Dockerfile:8
--------------------
   7 |
   8 | >>> RUN apt-get -q update && \
   9 | >>>     apt-get -qy dist-upgrade && \
  10 | >>>     apt-get -qy install libterm-readline-perl-perl dialog && \
  11 | >>>     apt-get -qy install sudo apt-utils software-properties-common xauth dialog
  12 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get -q update &&     apt-get -qy dist-upgrade &&     apt-get -qy install libterm-readline-perl-perl dialog &&     apt-get -qy install sudo apt-utils software-properties-common xauth dialog" did not complete successfully: exit code: 100

```

**Comment by nem8** [comment] 2024-08-26 13:34
Noticed this being open and unanswered. Just wanted to chime in that i set this up today and did NOT have the issues described above.

**Comment by niclan** [comment] 2024-08-27 13:54
Sorry, closing as I can't reproduce.

**Closed as not planned by niclan** 2024-08-27 13:54 UTC

**Comment by iMiMx** [comment] 2025-06-20 12:05
Just in case .... those that had problems - @kostecky @NoahJaehnert - were/are you on ARM/Apple Silicon, i.e non-x86?

If so:

`docker build --platform linux/amd64 -t javafox .`
